language: groovy

jdk:
  - openjdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: ./grailsw compile; ./grailsw test-app;